name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev    
    - name: Build
      run: cargo build --all --verbose --features bevy/dynamic
    - name: Test
      run: cargo test --features bevy/dynamic -- --nocapture --test-threads=1
